<?xml version="1.0"?>
<package format="2">
  <name>place_estimation</name>
  <version>0.0.1</version>

  <description>
    Prior distribution generation for Place position estimation
  </description>

  <maintainer email="soma@example.com">soma</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>

  <export/>
</package>
